### ISSUE TITLE
You've committed your AWS credentials

### ISSUE THREAD

**Issue by adamlwgriffiths** [hparik11/Amazon_Product_Review_Analysis#1]
Unless you want a massive bill, I suggest you remove this configuration file and de-authenticate these credentials.

https://github.com/hparik11/Amazon_Product_Review_Analysis/blob/master/amazon.cfg

For all intents and purposes, your account is now compromised.

https://securosis.com/blog/my-500-cloud-security-screwup

**Comment by hparik11** [comment]
Yea I have changed it.
